include $(ARUBA_SRC)/mk/Makefile.top

CFLAGS_LOCAL += -DHAVE_CONFIG_H
INCS_LOCAL := -I..

CFILES = ../usb.c ../error.c ../descriptors.c ../linux.c

LIBRARY = usb

include $(ARUBA_SRC)/mk/Makefile.bottom
