include $(ARUBA_SRC)/mk/Makefile.top

ifdef AP_PLATFORM

# - local defintions.
CFLAGS_LOCAL += 
INCS_LOCAL := -I.  -I$(ARUBA_SRC)/cmn 

CFILES= ifenslave.c

LIBS_LOCAL_PATH := 
LIBS_LOCAL :=

APPLICATION = ifenslave

endif
include $(ARUBA_SRC)/mk/Makefile.bottom

