include $(ARUBA_SRC)/mk/Makefile.top

DIRS_${AP_PLATFORM} += busybox-1.01 eject rezero utelnetd-0.1.3 brctl usb_modeswitch ndisc6-1.0.2 

DIRS_${MIPS_XLP_PLATFORM} += kernel_core_splitter
DIRS_${FAT_AP} += dnsmasq-2.55 dhcp-helper-1.0 tinyproxy ethtool-4.0 traceroute6 ntpd

include $(ARUBA_SRC)/mk/Makefile.bottom
