#
# All the DSOs are copied here as they are built.
# Applications can link against DSOs in here.
#
# At the end of the build, they are copied on the target.
# Also handles make clean.
#


include $(ARUBA_SRC)/mk/Makefile.top

#
# nothing...
# used for the clean target.
#

include $(ARUBA_SRC)/mk/Makefile.bottom
