#!/bin/sh
#
# Copyright (C) 2002-2011 by Aruba Networks, Inc.
# All Rights Reserved.
# 
# This software is an unpublished work and is protected by copyright and 
# trade secret law.  Unauthorized copying, redistribution or other use of 
# this work is prohibited.
#
# The above notice of copyright on this source code product does not indicate
# any actual or intended publication of such source code.
#
for i in ${IMAGE_VARS}; do
	j=$(echo $i | cut -d_ -f2)
	if [ X$j != X ]; then
		echo $i | cut -d_ -f1
		exit 0
	fi
done

for i in ${VARIANT_VARS}; do
	j=$(echo $i | cut -d_ -f2)
	if [ X$j != X ]; then
		echo $i | cut -d_ -f1
		exit 0
	fi
done
exit 1
